# Generated by Django 5.0.4 on 2024-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_city_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
