# Generated by Django 5.0.4 on 2024-05-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
