# Generated by Django 5.0.4 on 2024-05-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_city_alter_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
