# Generated by Django 5.0.4 on 2024-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='isDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
