# Generated by Django 5.0.4 on 2024-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subject_isdisabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
