# Generated by Django 5.0.4 on 2024-05-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
