# Generated by Django 5.0.4 on 2024-05-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_alter_booking_booking_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_intent', models.CharField(max_length=100)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_booking', to='booking.booking')),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_tutor', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
