# Generated by Django 5.0.4 on 2024-05-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tutor_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
